# Maven
# Build your Java project and run tests with Apache Maven.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/java

trigger:
  batch: true
  branches:
    include:
      - develop
      - master
      - release/*
  paths:
    include:
      - docs
    exclude:
      - docs/README.md

pool:
  vmImage: ubuntu-20.04

steps:
  - task: JavaToolInstaller@0
    inputs:
      versionSpec: '15'
      jdkArchitectureOption: 'x64'
      jdkSourceOption: AzureStorage
      azureResourceManagerEndpoint: '$(CDN_TARGET_CONNECTION)'
      azureStorageAccountName: '$(AZURE_STORAGE_ACCOUNT)'
      azureContainerName: shared
      azureCommonVirtualFile: 'openjdk-15.tar'
      jdkDestinationDirectory: '/opt'
      cleanDestinationDirectory: false

  - task: Bash@3
    inputs:
      targetType: 'inline'
      script: |
        echo 'JAVA_HOME = $(JAVA_HOME)'
        which java
        java --version

  - task: MavenAuthenticate@0
    inputs:
      artifactsFeeds: 'enterprise'
      mavenServiceConnections: 'enterprise-feed-connection'

  - task: Maven@3
    inputs:
      mavenPomFile: 'pom.xml'
      mavenOptions: '-Xmx3072m'
      javaHomeOption: 'path'
      jdkDirectory: '/opt/JAVA_HOME_15_X64_openjdk-15_tar/jdk-15'
      jdkArchitectureOption: 'x64'
      publishJUnitResults: false
      testResultsFiles: '**/surefire-reports/TEST-*.xml'
      goals: 'package deploy'

  - task: PublishBuildArtifacts@1
    enabled: false
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: 'smtz-integration-spec*.jar'
      publishLocation: 'Container'

  - task: PublishPipelineArtifact@1
    inputs:
      targetPath: '$(Pipeline.Workspace)/s/target/smtz-integration-spec-0.0.1-SNAPSHOT.jar'
      artifact: 'drop'
      publishLocation: 'pipeline'